name: denaro # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: denaro
#icon: NickvisionMoney.Shared/Resources/org.nickvision.money.png
source-code: https://github.com/nlogozzo/NickvisionMoney
issues: https://github.com/nlogozzo/NickvisionMoney/issues
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
layout:
  /usr/lib/org.nickvision.money:
    symlink: $SNAP/usr/lib/org.nickvision.money
  /usr/share/org.nickvision.money:
    symlink: $SNAP/usr/share/org.nickvision.money
parts:
  denaro:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
    #source-tag: 
    build-packages:
      - blueprint-compiler
      - wget
    override-pull: |
      craftctl default
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 7.0
      patch -p1 < $CRAFT_PROJECT_DIR/snap/denaro-snap.patch
    override-build: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools:$HOME/.cargo/bin
      cd $CRAFT_PART_SRC
      dotnet tool restore
      dotnet cake --target=Publish --prefix=/usr --ui=gnome --self-contained
      dotnet cake --target=Install --destdir=$CRAFT_PART_INSTALL
      #cp -r $CRAFT_PART_INSTALL/usr/share/icons $CRAFT_PART_INSTALL/usr
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in $(find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"); do
  	new_basename=$(basename $i | sed "s/org\.nickvision\.money/denaro/")
  	mv $i "$(dirname $i)/$new_basename"
      done

    parse-info: [ usr/share/metainfo/org.nickvision.money.metainfo.xml ]
  #symbolic-fix:
  #  after: [denaro]
  #  plugin: nil
  #  override-prime:
  #    set -eux
  #     $CRAFT_STAGE/usr/icons $CRAFT_PRIME/usr/share/
apps:
  denaro:
    command: usr/bin/org.nickvision.money
    extensions: [gnome]
    common-id: org.nickvision.money
    plugs:
      - home
      - removable-media
